version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      TQFl8j9QEC59NvL8CDZZdQ7lxWyedOKHEm3QDBD8vswiDlO9/v0+i5SOG/uEuGP+Z6/MM6mlb61O8uE9txCsiYk+s1YjErMohaOZ53+lKhZ1u76kKylagDGWsHCPDm3f5jLk1nuLXz6C6DHPa7A/cnd+e8Ug7RuBMYTvfBUzX7gArWP9fG0wBXtVxGzBMlZgcezVFegLjxv6SruyHa7YktGSX0uemLkrQb8Uo/G/zApvuUdgFCadZAUn10EvZrQkUu9SpicLHkuw9yw6v8CYvmHTFoVSiNz+QFACmgCHkW0ij7YKDrddm1eiR6iEzlcq+MlJo5gV+uvcusCeeZofWl+8liI0IwKM8TxGnchIGsWdGeGwj+cf4M2qAskVlCh7ZKNIJBeRyo0klT6PL6jcDgUA31YHGz5Jab190Wm8v5/4cRhRD6ZX30asGcyfADrGXWavG9wV/BjhcoOjFkFEsCDBJq6JcC+Lps3U9YE/E/8DCsUte4AyzHgyOQ/8QcoTaqujc4MjTDh3SEf+5/BLBkXz8voh1O74hTzVL3NKlQZBvc0qIBmCyLfvMZLR6Mc4QhllcrmUkixKEWBqcfR08MriVQSjPNAWdL08ogUejZcBaAY1Am4/K47IncYMT+HZhRrecC6Q84rOfu8DRtV+qZ73tbuJCrRTNf/kFl6c7Y0=
