version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      OVNYh+rMyTIa5hejyFzJ9kWmLx/IHMqZKEVIRQZ9uq7LgPp/QDGUmw+NH7zjArTcjWTcZEDoimvFZQ+Z+QbyIaZioqSZhJEhg5gcPOGDLY2pi05bzM9THXHTN053w338iR5lB8Cs+skFs2Rv27yJN+PHlIA8ByuxrCnN3sLaWE7vbe//C3nePWmDz1peqGXMi7fZw0VflHIhta0JI1XEeuFrSEz39HqhN+/sNpFQQCCo7IY7k50e8ViWli4tRHjJBAq1k0/4BjFCw9VcZhajrG5Rvd3r8B69n9TZJ33hQoA2+tbp0yk0RpWSUsKC2+o2TL9C6oXVn0ev53usT3hySeXAGROm6alzqEvPC+c4BkAzVB6j/qanmfwSDPavbZUFMPX4WEFy2eVjcVI9H071SxLf0Mod6RRmbXTxQMXRVVuTgzxiA+7XNZMmRZ216YiF/VWPix1z89PYXAlw25+cPOz7AhXBrKD1PWfV35Mw9hVjbCHWjyCPpCopLa4bOBuoaB4RBxlI5ZM9NmTg+9C9m836gkyNZVc6el47FAW43C3FPTkhucUnCL4Zq/QX0xlUYe1cq0KWvdkFxPf1BSHI1h7aa+baBxUFfxXpAZ1Jk/ty3mPc88O2dH7Scz1nN228g1py4VusttQii/BFOFglSKGYkOcvUkfc+DGsJXdoYK8=
