version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      vaFqF1VjDjTMJqfAmm+zoxqMZN+lVjRpA8M+SOKjjnmWTpQe6Tm3SKhEtW+RpcoMkZN4+0qJodefKev81rO2dijL/1KoZwCf/Wg+Uq8m/VS6FS4KvZxkgzTwGO3HVv6YyxXtxOkqwOn35LA27BfJZQVziSfomu054HkBnzc8AEkkvq+0TzTEwunW8e2gn+LpLAydoSEpdfJEZMwtLoAPRY+T/moFiHNfk9Xq7foovG3PgWpjqIGNF5mJpn+x4LtWtiK4wANfQ7kAyR6/dIMhsUYr846a46Qv0KXo/1pC2/mg2UO9Z4X0PAG3ms1S8vkIPBhV40les2jKn6bovogZyr5DR6yLAGI4OcbXflxrUp+2JEZsjtNhWtdukw5XGJOdzbD5TA1g0PXjYSsDhS0kOjtkZG1pQ9aPoveiHtoSPLBaladQSIDpNcpNaEtWTkasRx/69hilhVZnFvGIL8BSpSIJ1Q0/vQJ5WSmQYamJoJ6uzV3KiNQmgWrK/5QIGLzT+HIIyPKl4BS3VR51LVFEEZRXew3ax3g4yCbedK8jYIAG0e/pgwlcGND84ffYvpcGHYplMZxfbxvh+FPZ3BnpRbCmTEJ30JHnkQ/HM92uEDblFmskNhGAa3q1Pla5dPBd7BNoikEDgZEvQsArRP6TKRdxthWSVXK6nKnISxIdbgI=
