sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: S5qIjhSypGNCtlWraeLgtnbRlGL/RCGpcSGVScz7T7ZG0+inys3eRAWpmmnMAX66r3tK/iMHesNXUZr+/Kqx7zb2z8pcfmqX+zzfjWrA0Ct7x7RtkkxkZvk3TFqqO1drPBFxFATgYoO32pV5AvJ2flYIO/7O0LECAT9Am+ESWhBs2ecHjB3sQV+X9zI2LRM+I9GONl//6tf5BD7RhMqGLKPJeiGrVvzLBhpOerQf+VfF/3mKLGn8yugiGPvEuBUeyZasI1+Jjq50EO+e/N/qdbD8bIAxrulX2ZpJ4U5rra8t5eFv8tjPq/DPr8FXmfnXA/2vIqb7+PAjbFG5F+eUvEb+Ijm/dFgScD7Rk8eDRRGCn1+ua3sTG7cgulTtbJniQfmnEIpJwPCUnKbdbRXgrSkMakdKfRXO8i562RIouJzfAUuLh446sKY2tXKVYbLOzKyk4+r2wkJJ9bRKN/BZA8UWsWCn+BJOgossCnOIv7Iju5B5Bnt/TaYqJX5je+xk+/n4xZoKXRPRRjStHxuES0jkw8ZxL5GnykMpX+sewqG5HtmWEAB9egy0PjTkoj31n0WlKWnuYfz6LiEyAHYEXmMXmeK0PmgLJTsa2OYzsGsz6SI2BkihjCaqn6JQ4i+DhSeNfkpSl5sGpgVd/q+XK/XcrjtmWzoJLbar8rmYncQ=
