version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      Ofv1hTuTuFpbhSMQxyVPhNt63vkCZXhv+SDkde9fpOwvy4zNzSyYyZCbXpeInBAppzDhN4jkLW0tUCsyLMIdZkSImY8S4DrdLkgjGiglqO6qzKxxY7GO+kGotyQEgcZjHHdOzWgX7XnAEvJqDMnVWxEheqMfYWvQImD6hCrMEEyRShfDTNMAL78+IKPAXpuNteZIo0yfN6K+foxqnK90JifK3UsCy74tVhBvMFSFVbmBsusvYCacBR7KVYnxKRSoiQXRpY0ml6UnWtsaU9iwm9pffIy/9crr3UJl6LjyvWmaWyirltO6+zW5aquNKOJfOcCuIP5ozbRII864ZrnCmiQPAz0lRRYM8kUH0/WIOfjf35pWnuBp+mDB3Qaf0JrZbuGoDRTXFWij4iWCgzF/GCr+X/2uag1piblC3xneQxJdoXrzhAPPujyiI64JCQSR+NnODpTMekCrz8s6uYZW7osJN3rCjJB/ome0uVGo0CEhE2k6bguXMeWmaoGAf42SLUedrA0mVnHqnZSkZPuSX7aFg9CW8AatOojZnvLmDhuZafRSlAP161mVyyh20CSLaPMdZ6gFX8m8Z+QUcTPPhqRTRsaQzfXmboO3pnNb8u7cHAyOTlzRwdjqOlfYcUomfUZ10T0hfLtcxWfXYQ6Sub14XB0ckc4IYuUcj9l30j4=
